#!/bin/sh
#
#

CRUCIBLE_ENV="${CRUCIBLE_ENV:-development}"

if [ "${CRUCIBLE_ENV}" == "development" ]; then
  if [ "$#" -eq 0 ]; then
    CRUCIBLE_ARGS="./test/unit/*/*.js"
  else
    CRUCIBLE_ARGS="$@"
  fi

  truffle test --network ${CRUCIBLE_ENV} ${CRUCIBLE_ARGS} && \
    pkill -f ganache-cli
elif [ "${CRUCIBLE_ENV}" == "staging" ] || \
     [ "${CRUCIBLE_ENV}" == "ropsten" ] || \
     [ "${CRUCIBLE_ENV}" == "kovan" ]; then
  if [ "$#" -eq 0 ]; then
    CRUCIBLE_ARGS="./test/integration/*/*.js"
  else
    CRUCIBLE_ARGS="$@"
  fi

  truffle test --network ${CRUCIBLE_ENV} ${CRUCIBLE_ARGS}
elif [ "${CRUCIBLE_ENV}" == "production" ]; then
  if [ "$#" -eq 0 ]; then
    CRUCIBLE_ARGS="./test/production/*/*.js"
  else
    CRUCIBLE_ARGS="$@"
  fi

  truffle test --network ${CRUCIBLE_ENV} ${CRUCIBLE_ARGS}
fi
