#!/bin/sh -x
#
#

CRUCIBLE_ENV="${CRUCIBLE_ENV:-development}"

# if this is the staging env, then unseal the vault
if [ "${CRUCIBLE_ENV}" == "staging" ]; then
  ./scripts/vault_unseal.js
fi

# compile the solidity code
truffle compile --network ${CRUCIBLE_ENV}

# if this is the dev env, then startup a mock blockchain
if [ "${CRUCIBLE_ENV}" == "development" ]; then
  ./scripts/devchain
fi

# migrate contracts to the appropriate network
truffle migrate --network ${CRUCIBLE_ENV}

# run tests
if [ "${CRUCIBLE_ENV}" == "development" ]; then
  truffle test --network ${CRUCIBLE_ENV} ./test/unit/* && pkill -f ganache-cli
elif [ "${CRUCIBLE_ENV}" == "staging" ]; then
  npm run ${CRUCIBLE_ENV} &
  while ! /usr/bin/pgrep lite-server >/dev/null; do
    sleep 1
  done
  truffle test --network ${CRUCIBLE_ENV} ./test/integration/*
fi
