#!/bin/sh
#
#
mkdir -p ./snapshots/development
./scripts/snapchain
zos push --network development
zos create Foundry --init initialize \
  --args "0x5dee77e75a0f9e5272a02d67ce0bf9f3608355fe" --network development
pkill -f ganache-cli
